-- MySQL Script generated by MySQL Workbench
-- 10/08/17 21:39:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema medplusco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medplusco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medplusco` DEFAULT CHARACTER SET utf8 ;
USE `medplusco` ;

-- -----------------------------------------------------
-- Table `medplusco`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`empresas` (
  `emp_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(10) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `representante_legal` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_afiliacion` DATE NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `activo` VARCHAR(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `medplusco`.`planadm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`planadm` (
  `pa_id` INT NOT NULL,
  `id_administradora` INT(10) NOT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `codigo` VARCHAR(6) NOT NULL,
  `contrato` VARCHAR(45) NULL,
  `fechaini` DATE NULL,
  `fechafin` DATE NULL,
  `valor_contrato` DOUBLE NULL,
  `activo` VARCHAR(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`paid`),
  INDEX `planadm_idadministradora_index` (`idadministradora` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medplusco`.`administradoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`administradoras` (
  `adm_id` INT(10) NOT NULL,
  `codigo` VARCHAR(6) NOT NULL,
  `nit` INT(10) NOT NULL,
  `dv` INT(1) NULL DEFAULT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `representante_legal` VARCHAR(45) NULL DEFAULT NULL,
  `activo` INT(1) NOT NULL,
  `idempresa` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`adm_id`),
  INDEX `administradoras_idempresa_index` (`idempresa` ASC),
  CONSTRAINT `fk_administradoras_planadm`
    FOREIGN KEY (`adm_id`)
    REFERENCES `medplusco`.`planadm` (`id_administradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`municipios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mun_codigo` INT(11) NOT NULL,
  `mun_nombre` VARCHAR(35) CHARACTER SET 'utf8' NOT NULL,
  `dep_codigo` INT(2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`dep_codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1123
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `medplusco`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`departamentos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dep_codigo` INT(2) UNSIGNED NOT NULL,
  `dep_nombre` VARCHAR(35) CHARACTER SET 'utf8' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`dep_codigo` ASC),
  CONSTRAINT `fk`
    FOREIGN KEY (`dep_codigo`)
    REFERENCES `medplusco`.`municipios` (`dep_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `medplusco`.`diagnosticos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`diagnosticos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `coddiag` VARCHAR(6) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `descripcion` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `sexo` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13065
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`especialidades` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`hcgeneral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`hcgeneral` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `motivo_consulta` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `enfermedad_actual` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `fc` DOUBLE(3,2) NOT NULL,
  `fr` DOUBLE(3,2) NOT NULL,
  `presion` VARCHAR(7) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `temperatura` DOUBLE(3,2) NOT NULL,
  `talla` DOUBLE(3,2) NOT NULL,
  `peso` DOUBLE(3,2) NOT NULL,
  `indmasacorp` DOUBLE(3,2) NOT NULL,
  `antecedentes_personales` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `antecedentes_familiares` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `antecedentes_alergicos` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `antecedentesqx` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `craneo` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `torax` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `abdomen` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `piel` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `genito_urinario` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `extremidades` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `sistema_nervioso` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `finalidad_consulta` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tpodxppal` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `causa_externa` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dxppal` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dxrel1` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `dxrel2` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `dxrel3` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `plan` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tratamiento` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `recomendaciones` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `idpaciente` INT(10) NULL DEFAULT NULL,
  `idmedico` INT(10) NULL,
  `ideps` VARCHAR(255) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `hcgeneral_idpaciente_index` (`idpaciente` ASC),
  INDEX `hcgeneral_ideps_index` (`ideps` ASC),
  INDEX `hcgeneral_idmedico_index` (`idmedico` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`evolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`evolucion` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `detalles` TEXT(450) NULL,
  `enfermedad_actual` TEXT(450) NULL,
  `problema` TEXT(450) NULL,
  `subjetivo` VARCHAR(255) NULL,
  `obejtivo` VARCHAR(255) NULL,
  `analisis` VARCHAR(255) NULL,
  `plan` VARCHAR(255) NULL,
  `peso` VARCHAR(18) NULL,
  `tesion_sistolica` VARCHAR(18) NULL,
  `tension_diastolica` VARCHAR(18) NULL,
  `frecuencia_cardiaca` VARCHAR(18) NULL,
  `temperatura` VARCHAR(18) NULL,
  `frecuencia_respiratoria` VARCHAR(18) NULL,
  `talla` VARCHAR(18) NULL,
  `imc` VARCHAR(18) NULL,
  `cod_diag` VARCHAR(4) NULL,
  `cod_diag_rel1` VARCHAR(4) NULL,
  `cod_diag_rel2` VARCHAR(4) NULL,
  `cod_diag_rel3` VARCHAR(4) NULL,
  `impresion_diag` VARCHAR(45) NULL,
  `idpaciente` INT(10) NOT NULL,
  `idmedico` INT(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `evolucion_idpaciente_index` (`idpaciente` ASC),
  INDEX `evolucion_idmedico_index` (`idmedico` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medplusco`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`medicos` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `tpoid` VARCHAR(2) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `identificacion` VARCHAR(13) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `ppnombre` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `psnombre` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ppapellido` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `psapellido` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `sexo` VARCHAR(1) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `direccion` VARCHAR(80) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telefono` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `celular` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `departamento` VARCHAR(2) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `municipio` VARCHAR(5) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `registro` VARCHAR(12) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `firma` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `activo` INT(1) NOT NULL,
  `idespecialidad` INT(11) NOT NULL,
  `idusuario` INT(10) NULL DEFAULT NULL,
  `idempresa` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idempresa` (`idempresa` ASC),
  INDEX `idusuario` (`idusuario` ASC),
  CONSTRAINT `fk_medicos_hcgeneral`
    FOREIGN KEY (`id`)
    REFERENCES `medplusco`.`hcgeneral` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicos_evolucion`
    FOREIGN KEY (`id`)
    REFERENCES `medplusco`.`evolucion` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`pacientes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `tpoid` VARCHAR(2) NOT NULL,
  `pid` VARCHAR(13) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `ppnombre` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `psnombre` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ppapellido` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `psapellido` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `profesion` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fechanac` DATETIME NULL DEFAULT NULL,
  `sexo` VARCHAR(1) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `direccion` VARCHAR(80) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `telefono` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `celular` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `estado_civil` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `regimen` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `zona` VARCHAR(1) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `departamento` VARCHAR(2) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `municipio` VARCHAR(5) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `responsable` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel_responsable` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `acompanante` VARCHAR(45) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tel_acompanante` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `activo` INT(1) NOT NULL,
  `sangre` VARCHAR(2) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `etnia` VARCHAR(20) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `idadministradora` INT(10) NOT NULL,
  `idempresa` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pacientes_ideps_index` (`idadministradora` ASC),
  INDEX `pacientes_idempresa_index` (`idempresa` ASC),
  CONSTRAINT `fk_pacientes_hcgeneral`
    FOREIGN KEY (`id`)
    REFERENCES `medplusco`.`hcgeneral` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacientes_evolucion`
    FOREIGN KEY (`id`)
    REFERENCES `medplusco`.`evolucion` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`planadm_has_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`planadm_has_pacientes` (
  `planadm_id` INT NOT NULL,
  `pacientes_id` INT(10) NOT NULL,
  PRIMARY KEY (`planadm_id`, `pacientes_id`),
  INDEX `fk_planadm_has_pacientes_pacientes1_idx` (`pacientes_id` ASC),
  INDEX `fk_planadm_has_pacientes_planadm1_idx` (`planadm_id` ASC),
  CONSTRAINT `fk_planadm_has_pacientes_planadm1`
    FOREIGN KEY (`planadm_id`)
    REFERENCES `medplusco`.`planadm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planadm_has_pacientes_pacientes1`
    FOREIGN KEY (`pacientes_id`)
    REFERENCES `medplusco`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medplusco`.`empresas_has_administradoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`empresas_has_administradoras` (
  `empresas_id` INT(11) NOT NULL,
  `empresas_medicos_id` INT(10) NOT NULL,
  `administradoras_id` INT(10) NOT NULL,
  PRIMARY KEY (`empresas_id`, `empresas_medicos_id`, `administradoras_id`),
  INDEX `fk_empresas_has_administradoras_administradoras1_idx` (`administradoras_id` ASC),
  INDEX `fk_empresas_has_administradoras_empresas1_idx` (`empresas_id` ASC, `empresas_medicos_id` ASC),
  CONSTRAINT `fk_empresas_has_administradoras_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `medplusco`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_has_administradoras_administradoras1`
    FOREIGN KEY (`administradoras_id`)
    REFERENCES `medplusco`.`administradoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`empresas_has_medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`empresas_has_medicos` (
  `empresas_id` INT(11) NOT NULL,
  `medicos_id` INT(10) NOT NULL,
  PRIMARY KEY (`empresas_id`, `medicos_id`),
  INDEX `fk_empresas_has_medicos_medicos1_idx` (`medicos_id` ASC),
  INDEX `fk_empresas_has_medicos_empresas1_idx` (`empresas_id` ASC),
  CONSTRAINT `fk_empresas_has_medicos_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `medplusco`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_has_medicos_medicos1`
    FOREIGN KEY (`medicos_id`)
    REFERENCES `medplusco`.`medicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `medplusco`.`empresas_has_pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medplusco`.`empresas_has_pacientes` (
  `empresas_id` INT(11) NOT NULL,
  `pacientes_id` INT(10) NOT NULL,
  PRIMARY KEY (`empresas_id`, `pacientes_id`),
  INDEX `fk_empresas_has_pacientes_pacientes1_idx` (`pacientes_id` ASC),
  INDEX `fk_empresas_has_pacientes_empresas1_idx` (`empresas_id` ASC),
  CONSTRAINT `fk_empresas_has_pacientes_empresas1`
    FOREIGN KEY (`empresas_id`)
    REFERENCES `medplusco`.`empresas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresas_has_pacientes_pacientes1`
    FOREIGN KEY (`pacientes_id`)
    REFERENCES `medplusco`.`pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
